# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='sms.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\tsms.proto\";\n\x12SendMessageRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"J\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\treceiveid\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"+\n\x15ReceiveMessageRequest\x12\x12\n\nreceive_id\x18\x01 \x01(\t\"R\n\x16ReceiveMessageResponse\x12\x11\n\tsend_time\x18\x01 \x01(\t\x12\x14\n\x0cphone_number\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2\x80\x01\n\x03Sms\x12\x36\n\x07SendSMS\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse(\x01\x12\x41\n\x0eReceiveMessage\x12\x16.ReceiveMessageRequest\x1a\x17.ReceiveMessageResponseb\x06proto3')
)

_SENDMESSAGEREQUEST = _descriptor.Descriptor(
    name='SendMessageRequest',
    full_name='SendMessageRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='phone_number', full_name='SendMessageRequest.phone_number', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='content', full_name='SendMessageRequest.content', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=13,
    serialized_end=72,
)

_SENDMESSAGERESPONSE = _descriptor.Descriptor(
    name='SendMessageResponse',
    full_name='SendMessageResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='success', full_name='SendMessageResponse.success', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='receiveid', full_name='SendMessageResponse.receiveid', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='message', full_name='SendMessageResponse.message', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=74,
    serialized_end=148,
)

_RECEIVEMESSAGEREQUEST = _descriptor.Descriptor(
    name='ReceiveMessageRequest',
    full_name='ReceiveMessageRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='receive_id', full_name='ReceiveMessageRequest.receive_id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=150,
    serialized_end=193,
)

_RECEIVEMESSAGERESPONSE = _descriptor.Descriptor(
    name='ReceiveMessageResponse',
    full_name='ReceiveMessageResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='send_time', full_name='ReceiveMessageResponse.send_time', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='phone_number', full_name='ReceiveMessageResponse.phone_number', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='content', full_name='ReceiveMessageResponse.content', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=195,
    serialized_end=277,
)

DESCRIPTOR.message_types_by_name['SendMessageRequest'] = _SENDMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['SendMessageResponse'] = _SENDMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['ReceiveMessageRequest'] = _RECEIVEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveMessageResponse'] = _RECEIVEMESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMessageRequest = _reflection.GeneratedProtocolMessageType('SendMessageRequest', (_message.Message,), dict(
    DESCRIPTOR=_SENDMESSAGEREQUEST,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:SendMessageRequest)
))
_sym_db.RegisterMessage(SendMessageRequest)

SendMessageResponse = _reflection.GeneratedProtocolMessageType('SendMessageResponse', (_message.Message,), dict(
    DESCRIPTOR=_SENDMESSAGERESPONSE,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:SendMessageResponse)
))
_sym_db.RegisterMessage(SendMessageResponse)

ReceiveMessageRequest = _reflection.GeneratedProtocolMessageType('ReceiveMessageRequest', (_message.Message,), dict(
    DESCRIPTOR=_RECEIVEMESSAGEREQUEST,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:ReceiveMessageRequest)
))
_sym_db.RegisterMessage(ReceiveMessageRequest)

ReceiveMessageResponse = _reflection.GeneratedProtocolMessageType('ReceiveMessageResponse', (_message.Message,), dict(
    DESCRIPTOR=_RECEIVEMESSAGERESPONSE,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:ReceiveMessageResponse)
))
_sym_db.RegisterMessage(ReceiveMessageResponse)

_SMS = _descriptor.ServiceDescriptor(
    name='Sms',
    full_name='Sms',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=280,
    serialized_end=408,
    methods=[
        _descriptor.MethodDescriptor(
            name='SendSMS',
            full_name='Sms.SendSMS',
            index=0,
            containing_service=None,
            input_type=_SENDMESSAGEREQUEST,
            output_type=_SENDMESSAGERESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='ReceiveMessage',
            full_name='Sms.ReceiveMessage',
            index=1,
            containing_service=None,
            input_type=_RECEIVEMESSAGEREQUEST,
            output_type=_RECEIVEMESSAGERESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SMS)

DESCRIPTOR.services_by_name['Sms'] = _SMS

# @@protoc_insertion_point(module_scope)
