# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.sms_pb2 as sms__pb2


class SmsStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.SendSMS = channel.stream_unary(
            '/Sms/SendSMS',
            request_serializer=sms__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=sms__pb2.SendMessageResponse.FromString,
        )
        self.ReceiveMessage = channel.unary_unary(
            '/Sms/ReceiveMessage',
            request_serializer=sms__pb2.ReceiveMessageRequest.SerializeToString,
            response_deserializer=sms__pb2.ReceiveMessageResponse.FromString,
        )


class SmsServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SendSMS(self, request_iterator, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessage(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendSMS': grpc.stream_unary_rpc_method_handler(
            servicer.SendSMS,
            request_deserializer=sms__pb2.SendMessageRequest.FromString,
            response_serializer=sms__pb2.SendMessageResponse.SerializeToString,
        ),
        'ReceiveMessage': grpc.unary_unary_rpc_method_handler(
            servicer.ReceiveMessage,
            request_deserializer=sms__pb2.ReceiveMessageRequest.FromString,
            response_serializer=sms__pb2.ReceiveMessageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Sms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
