# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

import proto.jaccount_pb2 as jaccount__pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='sms.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b('\n\tsms.proto\x1a\x0ejaccount.proto\"D\n\x0bMessageInfo\x12\x10\n\x08phonenum\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\ntimestring\x18\x03 \x01(\t\"!\n\x0cPhoneNumbers\x12\x11\n\tphonenums\x18\x01 \x03(\t\"C\n\rMessagesPlain\x12!\n\nrecepients\x18\x01 \x01(\x0b\x32\r.PhoneNumbers\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\rMessagesInfos\x12\x1e\n\x08messages\x18\x01 \x03(\x0b\x32\x0c.MessageInfo2\xa5\x01\n\x03Sms\x12\x35\n\x11SendPlainMessages\x12\x0e.MessagesPlain\x1a\x10.GeneralResponse\x12\x35\n\x11SendInnovMessages\x12\x0e.MessagesInfos\x1a\x10.GeneralResponse\x12\x30\n\x0fReceiveMessages\x12\r.PhoneNumbers\x1a\x0e.MessagesInfosb\x06proto3'),
    dependencies=[jaccount__pb2.DESCRIPTOR, ])


_MESSAGEINFO = _descriptor.Descriptor(
    name='MessageInfo',
    full_name='MessageInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='phonenum', full_name='MessageInfo.phonenum', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='content', full_name='MessageInfo.content', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestring', full_name='MessageInfo.timestring', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=29,
    serialized_end=97,
)


_PHONENUMBERS = _descriptor.Descriptor(
    name='PhoneNumbers',
    full_name='PhoneNumbers',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='phonenums', full_name='PhoneNumbers.phonenums', index=0,
            number=1, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=99,
    serialized_end=132,
)


_MESSAGESPLAIN = _descriptor.Descriptor(
    name='MessagesPlain',
    full_name='MessagesPlain',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='recepients', full_name='MessagesPlain.recepients', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='content', full_name='MessagesPlain.content', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=134,
    serialized_end=201,
)


_MESSAGESINFOS = _descriptor.Descriptor(
    name='MessagesInfos',
    full_name='MessagesInfos',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='messages', full_name='MessagesInfos.messages', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=203,
    serialized_end=250,
)

_MESSAGESPLAIN.fields_by_name['recepients'].message_type = _PHONENUMBERS
_MESSAGESINFOS.fields_by_name['messages'].message_type = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['MessageInfo'] = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['PhoneNumbers'] = _PHONENUMBERS
DESCRIPTOR.message_types_by_name['MessagesPlain'] = _MESSAGESPLAIN
DESCRIPTOR.message_types_by_name['MessagesInfos'] = _MESSAGESINFOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageInfo = _reflection.GeneratedProtocolMessageType('MessageInfo', (_message.Message,), dict(
    DESCRIPTOR=_MESSAGEINFO,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:MessageInfo)
))
_sym_db.RegisterMessage(MessageInfo)

PhoneNumbers = _reflection.GeneratedProtocolMessageType('PhoneNumbers', (_message.Message,), dict(
    DESCRIPTOR=_PHONENUMBERS,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:PhoneNumbers)
))
_sym_db.RegisterMessage(PhoneNumbers)

MessagesPlain = _reflection.GeneratedProtocolMessageType('MessagesPlain', (_message.Message,), dict(
    DESCRIPTOR=_MESSAGESPLAIN,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:MessagesPlain)
))
_sym_db.RegisterMessage(MessagesPlain)

MessagesInfos = _reflection.GeneratedProtocolMessageType('MessagesInfos', (_message.Message,), dict(
    DESCRIPTOR=_MESSAGESINFOS,
    __module__='sms_pb2'
    # @@protoc_insertion_point(class_scope:MessagesInfos)
))
_sym_db.RegisterMessage(MessagesInfos)


_SMS = _descriptor.ServiceDescriptor(
    name='Sms',
    full_name='Sms',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=253,
    serialized_end=418,
    methods=[
        _descriptor.MethodDescriptor(
            name='SendPlainMessages',
            full_name='Sms.SendPlainMessages',
            index=0,
            containing_service=None,
            input_type=_MESSAGESPLAIN,
            output_type=jaccount__pb2._GENERALRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='SendInnovMessages',
            full_name='Sms.SendInnovMessages',
            index=1,
            containing_service=None,
            input_type=_MESSAGESINFOS,
            output_type=jaccount__pb2._GENERALRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='ReceiveMessages',
            full_name='Sms.ReceiveMessages',
            index=2,
            containing_service=None,
            input_type=_PHONENUMBERS,
            output_type=_MESSAGESINFOS,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SMS)

DESCRIPTOR.services_by_name['Sms'] = _SMS

# @@protoc_insertion_point(module_scope)
